global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'demo'
    static_configs:
      - targets:
        - 'localhost:10000'
        - 'localhost:10001'
        - 'localhost:10002'

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'instrumentation-example'
    static_configs:
      - targets: ['localhost:12345']

  - job_name: 'cpu-exporter'
    static_configs:
      - targets:
        - 'localhost:8000'
