global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'demo'
    static_configs:
      - targets:
          - 'localhost:10000'
          - 'localhost:10001'
          - 'localhost:10002'
    metric_relabel_configs:
      - action: keep
        source_labels: [__name__]
        regex: '(demo_|http_).*'

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'instrumentation-example'
    static_configs:
      - targets: ['localhost:12345']

  - job_name: 'cpu-exporter'
    static_configs:
      - targets:
          - 'localhost:8000'

  - job_name: 'consul-sd-demo'
    consul_sd_configs:
      - server: 'localhost:8500'
    relabel_configs:
      - action: keep
        source_labels: [__meta_consul_service]
        regex: demo
