global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'demo'
    static_configs:
      - targets:
        - 'localhost:10000'
        - 'localhost:10001'
        - 'localhost:10002'
    metric_relabel_configs:
      - action: keep
        source_labels: [__name__]
        regex: '(demo_|http_).*'

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'instrumentation-example'
    static_configs:
      - targets: ['localhost:12345']

  - job_name: 'cpu-exporter'
    static_configs:
      - targets:
        - 'localhost:8000'

  - job_name: 'consul-sd-demo'
    consul_sd_configs:
      - server: 'localhost:8500'
    relabel_configs:
      - action: keep
        source_labels: [__meta_consul_service]
        regex: demo

  - job_name: 'file-sd-demo'
    file_sd_configs:
      - files:
        - 'targets.yml'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module:
        - http_2xx # Look for an HTTP 200 response.
    static_configs:
      - targets: # Targets to probe through the Blackbox Exporter.
        - 'http://prometheus.io'
        - 'https://prometheus.io'
        - 'http://example.com:8080'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115 # Blackbox Exporter address.

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9091']
