receivers:
- name: test-receiver
  slack_configs:
  - api_url: ''
    username: 'Demo Alertmanager'
    channel: '#alertmanager'
    send_resolved: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: test-receiver
