receivers:
- name: test-receiver
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    username: 'Demo Alertmanager'
    channel: '#alertmanager'
    send_resolved: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: test-receiver
