global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: a

rule_files:
  - recording_rules.yml

scrape_configs:
  - job_name: 'demo'
    static_configs:
      - targets:
        - 'localhost:10000'
        - 'localhost:10001'
        - 'localhost:10002'
